namespace Njord.Ais.Interfaces
{
    public interface ITimestamp
    {
        /// <summary>
        /// UTC second when the report was generated by the electronic position system (EPFS) 
        /// (0-59, or 60 if time stamp is not available, which should also be the default value, 
        /// or 61 if positioning system is in manual input mode, or 62 if electronic position 
        /// fixing system operates in estimated (dead reckoning) mode, or 
        /// 63 if the positioning system is inoperative)
        /// </summary>
        public uint Timestamp { get; init; }
    }
}
